[package]
name = "eh-manager"
version = "0.1.0"
authors = ["pastchick3 <331604390@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
log = "0.4"
env_logger = "0.7"
tokio = { version = "0.2", features = ["full"] }
reqwest = "0.10"
rusqlite = { version = "0.24", features = ["bundled"] }
scraper = "0.12"
futures = "0.3"
regex = "1.3"
