[package]
name = "eh-manager"
version = "0.1.0"
authors = ["pastchick3 <pastchick3@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.10", features = ["cookies", "json"] }
bitflags = "1.2"
scraper = "0.12"
regex = "1.3"
serde = "1.0"
tokio = "0.2"
