[package]
name = "eh-crawler"
version = "0.3.0"
authors = ["pastchick3 <331604390@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
toml = "0.5"
serde = "1"
serde_derive = "1"
tokio = { version = "0.2", features = ["full"] }
reqwest = "0.10"
scraper = "0.12"
futures = "0.3"
regex = "1.4"
